### PR TITLE
fix: getting target temps when set to auto

### LINKED ISSUE #19: No bar visualization in auto mode
### Current Behavior

If the mode is set to auto there is no bar showing the current set temp:
406F674F-E684-40E6-924D-11465FC6E77A

### Expected Behavior

Same as in manual/heating mode:
1408720B-35C0-470A-8FA7-8D87B039B454

### Steps To Reproduce

Set the thermostat mode to auto

### Environment

```markdown
- OS: Ubuntu
- Node:
- Version: 2022.5.5
- Hassio: 2022.5.3
```

### Anything else?

These are the entity states from automatic mode:
423AF53D-B1D9-4722-BB1F-793AD88F51DA

and manual mode:
8B56105C-58C8-43E2-9779-DCC11FB1AE27

Thank you for this otherwise amazing addition to the mushroom project 👍
Greetings

### PR DESCRIPTION
**Pull request by ulic75**
closes #19

### CODE REVIEW

File: src/cards/thermostat-card/utils.ts [hunk 1]
```diff
@@ -16,10 +17,22 @@ export const getStepSize = (hass: HomeAssistant, entity: ClimateEntity): number
     return entity.attributes.target_temp_step ?? systemStep;
 };
 
+export const supportTargetTemperatureRange = (entity: ClimateEntity) => supportsFeature(entity, 2);
```
Comment (kevin-brown) [inline src/cards/thermostat-card/utils.ts:20]: I'm running into an issue here where my thermostat supports setting target ranges for auto/heat_cool but does not expose them for just heat or cool, so this is coming back as `true` but I've got undefined for both `target_temp_high` and `target_temp_low`. I'm thinking this should be guarded by both the feature check and the mode check to make sure we are only taking advantage of this feature in the modes it is supposed to be used for?
